# Generated by Django 3.2.3 on 2021-05-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kadicandidate',
            name='nickname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
