# Generated by Django 3.2.3 on 2021-05-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_kadicandidate_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kadicandidate',
            name='logo',
        ),
        migrations.AddField(
            model_name='kadicandidate',
            name='imageurl',
            field=models.CharField(default='default.png', max_length=20),
            preserve_default=False,
        ),
    ]
