# Generated by Django 3.2.3 on 2021-05-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20210523_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='classname',
            new_name='candidate',
        ),
    ]
