# Generated by Django 3.2.3 on 2021-05-23 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_rename_classname_vote_candidate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kadicandidate',
            options={'verbose_name': 'Kádi jelölt', 'verbose_name_plural': 'Kádi jelöltek'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Szavazat', 'verbose_name_plural': 'Szavazatok'},
        ),
        migrations.AlterModelOptions(
            name='voter',
            options={'verbose_name': 'Szavazó', 'verbose_name_plural': 'Szavazók'},
        ),
    ]
