# Generated by Django 3.2.3 on 2021-05-23 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20210523_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
