# Generated by Django 3.2.3 on 2021-06-07 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_vote_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kadicandidate',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='kadicandidate',
            name='imageurl',
        ),
        migrations.RemoveField(
            model_name='kadicandidate',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='kadicandidate',
            name='nickname',
        ),
        migrations.AddField(
            model_name='kadicandidate',
            name='name',
            field=models.CharField(default='', max_length=40, verbose_name='Név'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kadicandidate',
            name='classname',
            field=models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='Osztály'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='voting.kadicandidate', verbose_name='Jelölt'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Szavazat Ideje'),
        ),
    ]
