# Generated by Django 3.2.3 on 2021-06-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_auto_20210607_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Kezdés időpontja')),
                ('end', models.DateTimeField(verbose_name='Befejezés időpontja')),
            ],
        ),
    ]
