# Generated by Django 3.2.3 on 2021-06-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'Időszak', 'verbose_name_plural': 'Időszak'},
        ),
        migrations.AddField(
            model_name='kadicandidate',
            name='color',
            field=models.CharField(default='#ff00ff', max_length=20, verbose_name='Szín'),
            preserve_default=False,
        ),
    ]
